---

- hosts: devenvs
  become: true
  tasks:

  - name: include vars
    include_vars:
      file: vault.yml

  - name: install packages
    package:
      name:
        - docker
        - git
        - zsh
        - util-linux-user
      state: latest
      update_cache: yes

  - name: start docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: config default shell
    user:
      name: ec2-user
      shell: /usr/bin/zsh

  - name: create ssh key
    copy:
      content: "{{ github_private_key }}"
      dest: /home/ec2-user/.ssh/id_ed25519
      group: ec2-user
      owner: ec2-user
      mode: 0600

- hosts: devenvs
  become: false
  tasks:

  - name: create ssh config
    copy:
      content: |
        Host github_ssh_connection
          HostName github.com
          IdentityFile /home/ec2-user/.ssh/id_ed25519
      dest: /home/ec2-user/.ssh/config

  - name: clone this
    git:
      repo: git@github.com:mcrampon/mc_dotfiles.git
      dest: /home/ec2-user/mc_dotfiles
      clone: yes
      accept_hostkey: yes
      key_file: /home/ec2-user/.ssh/id_ed25519

  - name: create git config
    file:
      src: /home/ec2-user/mc_dotfiles/files/gitconfig
      dest: /home/ec2-user/.gitconfig
      state: link
